# Generated by Django 5.2 on 2025-04-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_suppliercertification_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercontact',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
