# Generated by Django 5.2 on 2025-04-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='file_type',
        ),
    ]
