# Generated by Django 5.2 on 2025-04-17 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lead_time', models.CharField(max_length=50)),
                ('minimum_order', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('provided_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='quotes.quote')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefits', models.TextField()),
                ('quote_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='quotes.quoteresponse')),
            ],
        ),
    ]
