# Generated by Django 5.2 on 2025-04-17 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quoteresponse_alternativeoption'),
        ('supplier', '0002_alter_suppliercertification_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteresponse',
            name='supplier',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='quote_responses', to='supplier.supplier'),
            preserve_default=False,
        ),
    ]
