# Generated by Django 5.2 on 2025-04-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quoteresponse_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteResponseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quote_response_attachments/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotes.quoteresponse')),
            ],
        ),
    ]
