# Generated by Django 5.2 on 2025-04-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplierreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
